### PR TITLE
added csvview, mdview, imageview, and updated codedit to include ment…

### PR DESCRIPTION
**Pull request by gonzolively**
I added csvview, mdview, imageview, and updated codeedit to include the mention of a markdown previewer. I also added options to `remote:new` as there were tons of options that had no explanations.

### CODE REVIEW

**Comment by gonzolively** [comment]
@sawka

**Comment by sawka** [comment]
Ah, saw a reference to "webshare" in this PR.  Realized we dropped that feature and those command should be removed.

**Comment by gonzolively** [comment]
> Ah, saw a reference to "webshare" in this PR. Realized we dropped that feature and those command should be removed.

Good catch! I meant to ask you about that. I was surprised I didn't know about that feature yet.

**Comment by gonzolively** [comment]
@sawka , @mikeatwave should be good for merging now! I also removed the webshare stuff.

**Pull request merged**
